### ISSUE TITLE
ProstateX dataset‘s segmentation mask

### ISSUE THREAD

**Issue by Happy-life-echo** [aL3x-O-o-Hung/CAT-Net#1]
Thank you very much for your constructive work, but I have a question. I didn't find the segmentation mask for the ProstateX dataset, could you please let me know how to download it? If you annotated it yourself, can you share it with us? Thank you very much for your help if possible.

**Comment by aL3x-O-o-Hung** [comment]
Please refer to the dataset here (https://github.com/ykl-ucla/prostate_zonal_seg/tree/master/DATASET). There was some preprocessing done since some of the images here have different sizes. I do not think I have the code for the preprocessing or the training split at the moment but here is the data. Please let me know if you have any questions!

**Comment by Happy-life-echo** [comment]
Thank you very much for your reply, it is very helpful to me.
